# Generated by Django 4.1.1 on 2022-10-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='update_at',
        ),
    ]
